### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ltfschoen** [petuum/composing_information_system#27]
When I follow the QA.md instructions and run `python examples/pipeline/inference/search_cord19.py` to start the QA pipeline, I get the following output since I'm using a macOS with older 10.14.6, and because CUDA is not supported with macOS because I understand they typically don't have Nvidia GPUs.

But I wouldn't have though this would happen because in that search_cord19.py file it has a line of code `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`, which indicates to me that it would use cpu only if CUDA wasn't available on the macOS device.

```
Installing collected packages: en-ner-jnlpba-md
Successfully installed en-ner-jnlpba-md-0.3.0
Traceback (most recent call last):
  File "examples/pipeline/inference/search_cord19.py", line 90, in <module>
    nlp.initialize()
  File "/Users/cuttlefish/.pyenv/versions/3.7.13/lib/python3.7/site-packages/forte/pipeline.py", line 710, in initialize
    self.initialize_components()
    ...
  File "/Users/cuttlefish/.pyenv/versions/3.7.13/lib/python3.7/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Note that this could be as simple as just running `export CUDA_VISIBLE_DEVICES=""` before running  `python examples/pipeline/inference/search_cord19.py`. See other alternatives here https://stackoverflow.com/questions/53266350/how-to-tell-pytorch-to-not-use-the-gpu

**Comment by ltfschoen** [comment]
Note that this could be as simple as just running `export CUDA_VISIBLE_DEVICES=""` before running  `python examples/pipeline/inference/search_cord19.py`. See other alternatives here https://stackoverflow.com/questions/53266350/how-to-tell-pytorch-to-not-use-the-gpu

**Comment by ltfschoen** [comment]
this was actually an easy fix
* view current video cards
```
lspci | grep VGA
```
* first checked if CUDA (support for multiple GPUs) is available on your machine
```
python -c 'import torch; print(torch.cuda.is_available())'
python -c 'import torch; print(torch.cuda.device_count())'
python -c 'import torch; print(torch.cuda.is_available())'
python -c 'import torch; print(torch.version.cuda)'
```
* change to match number of GPU's available https://docs.allennlp.org/v2.2.0/CHANGELOG/#added_15
  * if two GPUs `'cuda_devices': [0, 1]` or if 3x `[0, 1, 2]` https://blog.allenai.org/tutorial-how-to-train-with-multiple-gpus-in-allennlp-c4d7c17eb6d6
  * if no GPUs `'cuda_devices': [-1, -1]`, where use amount of CPUs available as the index count. 
    * didn't use all CPUs so can do other stuff too
